// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package types

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompleteStepRequest) DeepCopyInto(out *CompleteStepRequest) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompleteStepRequest.
func (in *CompleteStepRequest) DeepCopy() *CompleteStepRequest {
	if in == nil {
		return nil
	}
	out := new(CompleteStepRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompleteStepResponse) DeepCopyInto(out *CompleteStepResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompleteStepResponse.
func (in *CompleteStepResponse) DeepCopy() *CompleteStepResponse {
	if in == nil {
		return nil
	}
	out := new(CompleteStepResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Runners != nil {
		in, out := &in.Runners, &out.Runners
		*out = make([]RunnerInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListGroupNameRequest) DeepCopyInto(out *ListGroupNameRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListGroupNameRequest.
func (in *ListGroupNameRequest) DeepCopy() *ListGroupNameRequest {
	if in == nil {
		return nil
	}
	out := new(ListGroupNameRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListGroupNameResponse) DeepCopyInto(out *ListGroupNameResponse) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListGroupNameResponse.
func (in *ListGroupNameResponse) DeepCopy() *ListGroupNameResponse {
	if in == nil {
		return nil
	}
	out := new(ListGroupNameResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListNamespaceRequest) DeepCopyInto(out *ListNamespaceRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListNamespaceRequest.
func (in *ListNamespaceRequest) DeepCopy() *ListNamespaceRequest {
	if in == nil {
		return nil
	}
	out := new(ListNamespaceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListNamespaceResponse) DeepCopyInto(out *ListNamespaceResponse) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListNamespaceResponse.
func (in *ListNamespaceResponse) DeepCopy() *ListNamespaceResponse {
	if in == nil {
		return nil
	}
	out := new(ListNamespaceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListRecordsRequest) DeepCopyInto(out *ListRecordsRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListRecordsRequest.
func (in *ListRecordsRequest) DeepCopy() *ListRecordsRequest {
	if in == nil {
		return nil
	}
	out := new(ListRecordsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListRecordsResponse) DeepCopyInto(out *ListRecordsResponse) {
	*out = *in
	out.Params = in.Params
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]Record, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListRecordsResponse.
func (in *ListRecordsResponse) DeepCopy() *ListRecordsResponse {
	if in == nil {
		return nil
	}
	out := new(ListRecordsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListRunnerRequest) DeepCopyInto(out *ListRunnerRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListRunnerRequest.
func (in *ListRunnerRequest) DeepCopy() *ListRunnerRequest {
	if in == nil {
		return nil
	}
	out := new(ListRunnerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListRunnerResponse) DeepCopyInto(out *ListRunnerResponse) {
	*out = *in
	if in.Runners != nil {
		in, out := &in.Runners, &out.Runners
		*out = make([]RunnerInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListRunnerResponse.
func (in *ListRunnerResponse) DeepCopy() *ListRunnerResponse {
	if in == nil {
		return nil
	}
	out := new(ListRunnerResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogStreamRequest) DeepCopyInto(out *LogStreamRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogStreamRequest.
func (in *LogStreamRequest) DeepCopy() *LogStreamRequest {
	if in == nil {
		return nil
	}
	out := new(LogStreamRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogStreamResponse) DeepCopyInto(out *LogStreamResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogStreamResponse.
func (in *LogStreamResponse) DeepCopy() *LogStreamResponse {
	if in == nil {
		return nil
	}
	out := new(LogStreamResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingRequest) DeepCopyInto(out *PingRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingRequest.
func (in *PingRequest) DeepCopy() *PingRequest {
	if in == nil {
		return nil
	}
	out := new(PingRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PongResponse) DeepCopyInto(out *PongResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PongResponse.
func (in *PongResponse) DeepCopy() *PongResponse {
	if in == nil {
		return nil
	}
	out := new(PongResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Record) DeepCopyInto(out *Record) {
	*out = *in
	if in.StepInfo != nil {
		in, out := &in.StepInfo, &out.StepInfo
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Record.
func (in *Record) DeepCopy() *Record {
	if in == nil {
		return nil
	}
	out := new(Record)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegisterRunnerRequest) DeepCopyInto(out *RegisterRunnerRequest) {
	*out = *in
	in.RunnerInfo.DeepCopyInto(&out.RunnerInfo)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegisterRunnerRequest.
func (in *RegisterRunnerRequest) DeepCopy() *RegisterRunnerRequest {
	if in == nil {
		return nil
	}
	out := new(RegisterRunnerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegisterRunnerResponse) DeepCopyInto(out *RegisterRunnerResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegisterRunnerResponse.
func (in *RegisterRunnerResponse) DeepCopy() *RegisterRunnerResponse {
	if in == nil {
		return nil
	}
	out := new(RegisterRunnerResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Request) DeepCopyInto(out *Request) {
	*out = *in
	out.Type = in.Type
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Request.
func (in *Request) DeepCopy() *Request {
	if in == nil {
		return nil
	}
	out := new(Request)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Response) DeepCopyInto(out *Response) {
	*out = *in
	out.Type = in.Type
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Response.
func (in *Response) DeepCopy() *Response {
	if in == nil {
		return nil
	}
	out := new(Response)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Result) DeepCopyInto(out *Result) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Result.
func (in *Result) DeepCopy() *Result {
	if in == nil {
		return nil
	}
	out := new(Result)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunStepRequest) DeepCopyInto(out *RunStepRequest) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunStepRequest.
func (in *RunStepRequest) DeepCopy() *RunStepRequest {
	if in == nil {
		return nil
	}
	out := new(RunStepRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunStepResponse) DeepCopyInto(out *RunStepResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunStepResponse.
func (in *RunStepResponse) DeepCopy() *RunStepResponse {
	if in == nil {
		return nil
	}
	out := new(RunStepResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerInfo) DeepCopyInto(out *RunnerInfo) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]Step, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerInfo.
func (in *RunnerInfo) DeepCopy() *RunnerInfo {
	if in == nil {
		return nil
	}
	out := new(RunnerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UploadFiles != nil {
		in, out := &in.UploadFiles, &out.UploadFiles
		*out = make([]UploadFile, len(*in))
		copy(*out, *in)
	}
	if in.WriteFiles != nil {
		in, out := &in.WriteFiles, &out.WriteFiles
		*out = make([]WriteFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Remarks != nil {
		in, out := &in.Remarks, &out.Remarks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SharingData != nil {
		in, out := &in.SharingData, &out.SharingData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	if in.Runners != nil {
		in, out := &in.Runners, &out.Runners
		*out = make(map[string]RunnerInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Type) DeepCopyInto(out *Type) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Type.
func (in *Type) DeepCopy() *Type {
	if in == nil {
		return nil
	}
	out := new(Type)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStepRequest) DeepCopyInto(out *UpdateStepRequest) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStepRequest.
func (in *UpdateStepRequest) DeepCopy() *UpdateStepRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateStepRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStepResponse) DeepCopyInto(out *UpdateStepResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStepResponse.
func (in *UpdateStepResponse) DeepCopy() *UpdateStepResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateStepResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadFile) DeepCopyInto(out *UploadFile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadFile.
func (in *UploadFile) DeepCopy() *UploadFile {
	if in == nil {
		return nil
	}
	out := new(UploadFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteFile) DeepCopyInto(out *WriteFile) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteFile.
func (in *WriteFile) DeepCopy() *WriteFile {
	if in == nil {
		return nil
	}
	out := new(WriteFile)
	in.DeepCopyInto(out)
	return out
}
